### ISSUE TITLE
Oversample

### ISSUE THREAD

**Issue by morvael** [ketura/LotR-TCG_card_generator#11]
Please add oversample = 2 for original sized cards to make the rendered charaters 100% more pretty.

Take into account adding oversample breaks hardcoded vertical spacing between gametext and lore text.

**Comment by ketura** [comment]
This is two issues in one: the hardcoded vertical spacing needs altered to be percentage based, and OVERSAMPLE should be added to the same IF/ELSE block that determines DPI.

**Comment by morvael** [comment]
Fixed lore spacing by removing extra line breaks (not required since lore and promo tags are treated like divs, they always start from new line):
```
[card_full_text] = JOIN([game_text],<lore>,[lore],</lore><promo>,[promocaps],</promo>)

[card_full_text] = REPLACE([card_full_text], <lore></lore>, "")
[card_full_text] = REPLACE([card_full_text], <promo></promo>, "")
```
and reduced margins:
```
HTMLMARGINS=promo,1.0%,0,0,0

IF= [lore_spacing] <> ""
    HTMLMARGINS=lore,1.0%,0,0,0,,[lore_spacing]
ELSE
    HTMLMARGINS=lore,1.0%,0,0,0,,[default_lore_spacing]
ENDIF
```
