### ISSUE TITLE
Ring icon replacement

### ISSUE THREAD

**Issue by morvael** [ketura/LotR-TCG_card_generator#16]
I think it's not defined. If I'm correct this is the code that does it:
```
HTMLKEY=,"(O)","&#9675",typesymbol
HTMLKEY=,"\91\O\93\","&#9675",typesymbol
```
(O) and [O] replaced to ring symbol. Used by Legends Masterworks cards as their rarity,

**Comment by ketura** [comment]
In the collector's info only, O will now be replaced with the ring symbol ("○") and have its font set to use the game text font, which has that symbol embedded.
