### ISSUE TITLE
Ring-bearer replacement

### ISSUE THREAD

**Issue by morvael** [ketura/LotR-TCG_card_generator#17]
Please add automatic "Ring-bearer." replacement (for new cards, old-style cards have to be done by hand: "<b>Ring-bearer (resistance 10).</b> ").

**Comment by morvael** [comment]
What about new style ring-bearer (just "Ring-bearer.")

**Comment by ketura** [comment]
This should work for both `Ring-bearer.` and `Ring-bearer (resistance X).`, the only limitation being that X is between 1-15 (which I think is reasonable).

**Comment by morvael** [comment]
```
HTMLKEY=,"Ring-bearer (","<b>Ring-bearer (</b>",,C
```
well it looks for (

**Comment by ketura** [comment]
Ah, I left out the line I thought I had included.  Fixed.
