### ISSUE TITLE
Possible new replacements

### ISSUE THREAD

**Issue by morvael** [ketura/LotR-TCG_card_generator#3]
Real minus − instead of - when followed by number.
<br> alternative: pipe |

**Comment by morvael** [comment]
Alternative: -- replaced with − (so to let people have choice).

**Comment by ketura** [comment]
I didn't notice that dashes are always en dashes in game text.  I have added a rule for game text only that automatically replaces all dashes in front of digits with an en dash (so as to preserve regular dashes in e.g. "Half-troll").  I have also added a global rule that -- will get replaced with an en dash, and --- with an em dash, when longer dashes are manually desired.  The Aid keyword already automatically replaced "Aid - " with an em dash.

**Comment by ketura** [comment]
I have added a setting to replace a configurable string with <br>, tho [, ], (, ), or | are not supported on their own, and | is not supported in any combination ([n] however is a valid usage).
