### ISSUE TITLE
full_portrait not working in some combinations

### ISSUE THREAD

**Issue by morvael** [ketura/LotR-TCG_card_generator#30]
Currently full_portrait works correctly only for cards with full_art also set. But for full_art cards full_portrait shouldn't even be required. And for some cards I want only full_portrait.

Please make sure the following combinations work:
`full_art` (should be equal to `full_art full_portrait`)
`full_portrait`
`full_portrait no_rotate`

**Comment by morvael** [comment]
1st I need for character/modifier cards with their own "template" including picture (rings, countdown, some masterworks).
2nd I need for other cards, except sites.
3rd I need for sites.

**Comment by ketura** [comment]
The issue here is one of miscommunication over the intent and usage of full_art and full_portrait, I believe.  I'm going to add more intuitive names for the tags as aliases, and update the documentation accordingly.

**Comment by ketura** [comment]
I have added aliases for these two.

full_art is now no_template
full_portrait is now portrait_backdrop

The old ones can be used, but documentation is updated to refer to the new ones, instead.
