### ISSUE TITLE
Problem with Towers replacement

### ISSUE THREAD

**Issue by morvael** [ketura/LotR-TCG_card_generator#4]
It's impossible to write "th" (as in 4th), as it's automatically replaced with towers block symbol. Please consider using (T) or [towers] instead of just plain NUMBERt.

**Comment by morvael** [comment]
Same treatment for King block for consistency purposes.

**Comment by ketura** [comment]
The reason to keep this syntax intact is because it's the convention on TLHH, which I am aiming to preserve.  

Adjusted the 3T/3K replacement to be case-sensitive, which should address this particular case (as I don't think "4TH" should show up anywhere legitimately).
