### ISSUE TITLE
Promo card lore text

### ISSUE THREAD

**Issue by morvael** [ketura/LotR-TCG_card_generator#6]
Please allow easy use of promo card lore text using title and subtitle font, as well as being centered. Like in the following card:
http://lotrtcgwiki.com/wiki/lotr00019
http://lotrtcgwiki.com/wiki/lotr00021
http://lotrtcgwiki.com/wiki/lotr00028

**Comment by ketura** [comment]
Reworking to include this should also include a rework for helper text and/or configuration for custom text formats.

**Comment by morvael** [comment]
For now I'm content after adding
```
SETFONT= promolore,[title_font],{title_font_size?§},[default_character_title_font_size],D,{game_text_color?§},[default_game_text_color],CENTER
```
to nde file. However that doesn't make them uppercased.

**Comment by morvael** [comment]
I'd love to see this done via tag which simply changes lore field rendering method from left-aligned italics to centered, bolded, and using small caps.

**Comment by ketura** [comment]
Addressed both promo text and helper text.  In the future will need to try and find a better-fitting font.
